# Starship prompt - minimal & fast
# Install: brew install starship
# Add to zshrc: eval "$(starship init zsh)"

format = "$directory$git_branch$git_status$character"

right_format = "$cmd_duration$time"

[directory]
truncate_to_repo = false
truncation_length = 0
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "Â·"
style = "bright-black"

[git_status]
style = "bold red"
format = "[[*$modified$staged$deleted](yellow bold)]($style)"
modified = "*"
staged = "+"
deleted = "-"

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
format = "[$time]($style) "
style = "dimmed"
disabled = false
